source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.6'
gem 'devise'
gem 'cancan'
gem "paperclip", "~> 4.2"
gem 'ancestry'
gem 'kaminari' 
gem 'ckeditor'
gem "rails-settings-cached", "0.4.1"
gem 'acts-as-taggable-on'
gem 'nokogiri'

#gem 'liquid'
gem 'formtastic' 
gem 'formtastic-bootstrap' # This is must for form edit 
#gem "nested_form"
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
#gem 'therubyracer', platforms: :ruby # This cause asset error
gem 'therubyracer', '0.11.3', platforms: :ruby

# Use SCSS for stylesheets
gem 'sass-rails'#, '~> 4.0.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier'#, '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
#gem 'coffee-rails'#, '~> 4.0.0'


# Use jquery as the JavaScript library
# gem 'jquery-rails' # Add it in assets

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
#gem 'jbuilder'#, '~> 1.2'

group :development do
  gem 'sqlite3'
  gem 'mysql2'   
  gem 'debugger2'  
  #gem "nifty-generators"
end
group :production  do
  gem 'pg'
  gem 'rails_12factor'  
  #gem 'mysql2'  
  #gem 'therubyracer', :platforms => :ruby 
end

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.1.2'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
